name: Handle Dispatch Event

on:
  repository_dispatch:
    types: [trigger-workflow]

jobs:
  handle:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.client_payload.ref }}  # Use the branch specified in the payload

      - name: Run Build
        run: echo "Building on branch ${{ github.event.client_payload.ref }} with SHA ${{ github.event.client_payload.sha }}"
